GET http://localhost:5000/api/elections/61b6df36b14ab30011e9a691 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiaWQiOiI2MWUxMDYwZWZkNGJkNzAwMTYxNTA3ODAiLCJlbWFpbCI6ImhhcnNoYWwyNTAxMjAwMUBnbWFpbC5jb20iLCJhdXRoTGV2ZWwyIjp0cnVlLCJpYXQiOjE2NDI1MTg4OTksImV4cCI6MTY0MjYwNTI5OX0.XSV39_blGb8j6aOrILpcuNU5rYBMhIfPPMxhmKBcglc3EILGVulMYLpbS4i3PC9GEofyFsTlDaLAXwywz-MajKYAh4clnntgo9nHYklrsvWRkcEyQwc11BataI7o79nR5m7Zo-zAhZS7WGzRuL2U_tXn9zmDrWGV7Pi0ZZNPOD8

# POST http://localhost:5000/api/register/61b6df36b14ab30011e9a691 HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiaWQiOiI2MWUxMDYwZWZkNGJkNzAwMTYxNTA3ODAiLCJlbWFpbCI6ImhhcnNoYWwyNTAxMjAwMUBnbWFpbC5jb20iLCJhdXRoTGV2ZWwyIjp0cnVlLCJpYXQiOjE2NDI1MTg4OTksImV4cCI6MTY0MjYwNTI5OX0.XSV39_blGb8j6aOrILpcuNU5rYBMhIfPPMxhmKBcglc3EILGVulMYLpbS4i3PC9GEofyFsTlDaLAXwywz-MajKYAh4clnntgo9nHYklrsvWRkcEyQwc11BataI7o79nR5m7Zo-zAhZS7WGzRuL2U_tXn9zmDrWGV7Pi0ZZNPOD8


